name: Update Version and Publish
on:
  push:
    branches:
      - main
permissions:
  contents: write
env:
  GIT_USERNAME: 'yoad-rashty'
  GIT_EMAIL: 'yoad-rashty@users.noreply.github.com'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: node
        uses: actions/setup-node@v2
        with:
            node-version: 12
            registry-url: https://registry.npmjs.org
      - run: git config --global user.email "${{ inputs.git_email }}"
        shell: bash
      - run: git config --global user.name "${{ inputs.git_username }}"
        shell: bash
      - run: 'npm version patch'
        shell: bash
        env:
          GH_RELEASE_GITHUB_API_TOKEN: ${{secrets.NPM_BUMP_ACTOR_TOKEN}}
      - run: echo "release-tag=$(git describe --tags)" >> $GITHUB_OUTPUT
        id: release-tag-retriever
        shell: bash
      - run: |
          if [ $push_version_commit = "true" ]; then
            git push --follow-tags
          else
            echo "Skipping git push --follow-tags"
          fi
        shell: bash
        env:
          GH_TOKEN: ${{ inputs.github_token }}
          push_version_commit: true
      - run: 'npm i && npm run prepublish && npm publish --access public'
        shell: bash
        env:
          GH_RELEASE_GITHUB_API_TOKEN: ${{secrets.NPM_BUMP_ACTOR_TOKEN}}
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}
