name: Bump Version
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: node
        uses: actions/setup-node@v2
        with:
            node-version: 12
            registry-url: https://registry.npmjs.org
      - name: NPM-Version
        # You may pin to the exact commit or the version.
        # uses: Reedyuk/NPM-Version@805800379b213c9193ede2c7a7f14a1a99e4d10b
        uses: Reedyuk/NPM-Version@1.2.1
        with:
          # This will be the version you want to set in the package.json file
          version: 'patch'
          # The location of the package.json file, defaults to current directory.
#           package: # default is ./
          # If set to true, the version will be tagged and committed. Same behaviour as git-tag-version
#           git-tag-version: # optional
#       - name: npm version and publish
#         uses: geemanjs/conventional-changelog-npm-publish@1.0.0
#         env:
#           NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
#         with:
          # After the version is incremented - the user that makes the commit
#           author_email: 'roman-glassix@users.noreply.github.com'
          # After the version is incremented - the user that makes the commit
#           author_name: 'Roman-Glassix'
          # Commit message - [VERSION_TYPE] is replaced with either patch, minor or major
#           commit_message: # optional, default is Bumping [VERSION_TYPE] version
#       - name: Bump version
#         run: |
#           git config --global user.name 'Roman-Glassix'
#           git config --global user.email 'roman-glassix@users.noreply.github.com'
#           npm run version-update
