name: "Bump Version on main"
on:
  push:
    branches:
      - "main"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Current Version Checkout
        run: npm run version

      - name: 'run version change'
        uses: ./
        with:
          version: '10.1.1'

      - name: Current Version Checkout
        run: npm run version
