name: "Bump Version"
on:
  push:
    branches:
      - "main"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Bump version
        run: npm run version-update
#       - name: Commit
#         uses: peter-evans/create-pull-request@v1
#         with:
#           token: ${{ secrets.GITHUB_TOKEN }}
#           commit-message: Bump version
#           title: Bump version
