name: Update Version and Publish
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
#       - name: Checkout
#         uses: actions/checkout@master
#       - name: node
#         uses: actions/setup-node@v2
#         with:
#             node-version: 12
#             registry-url: https://registry.npmjs.org
      - name: Update NPM version and Publish to npmjs.org
        uses: bcomnes/npm-bump@v2.2.1
        with:
          # The email address used to create the version commit with.
          git_email: 'roman-glassix@users.noreply.github.com'
          # The name to use for the version commit. e.g. github.actor
          git_username: 'Roman-Glassix'
          # The version bump type to perform (e.g. major, minor, patch). See npm version docs for more info.  Pass this as an interactive variable.
          newversion: 'patch'
          # Run git push --follow-tags after running npm version.  Enable this if you dont configure a prepublishOnly hook that pushes git commits.
          push_version_commit: true
          # The command to run after npm version.  Useful if you are just using npm to version a package, but not publish to npm (like an action).
          publish_cmd: 'npm publish --access public'
          # Pass the secrets.GITHUB_TOKEN to enable gh-release capabilities.
          github_token: ${{secrets.GITHUB_TOKEN}}
          # An npm token scoped for publishing.  Used to create the release.
          npm_token: ${{secrets.NPM_AUTH_TOKEN}}
